### ISSUE TITLE
Document set up of ABCL aio

### ISSUE THREAD

**Issue by alanruttenberg** [alanruttenberg/lsw2#4]

**Comment by jonathanbona** [comment]
I'd be happy to make some suggested edits to the README based on my recent experience setting up LSW on a new machine. Commit my suggestions directly to owlapiv4 branch or?

**Comment by alanruttenberg** [comment]
Commit directly. Thanks!

**Comment by jonathanbona** [comment]
Documented well enough to save me personally a lot of time if I run across this again in the future:
https://github.com/alanruttenberg/lsw2/commit/159fcef8f877248fa7e8b252033bf63cd1f31fc6
