### ISSUE TITLE
SBCL instead ABCL

### ISSUE THREAD

**Issue by vanangamudi** [alanruttenberg/lsw2#6]
Is it possible to run LSW  over SBLC or CCL instead of depending upon Java?

**Comment by arademaker** [comment]
I suspect the answer will be no. It depend on Jena library as far as I understood.

**Comment by easye** [comment]
> I suspect the answer will be no. It depend on Jena library as far as I understood.

That is correct:  LSW is pretty intertwined with Java via ABCL that running it on another Common Lisp implementation would not be easily possible.
